name: package-manager-ci

on:
  push:
    branches:
     - main
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
    uses: fastify/workflows/.github/workflows/plugins-ci-package-manager.yml@2073dc8e1f9e172bf42daa3843c9dbd31af1e8cb # v6.0.0
