name: package-manager-ci

on:
  push:
    branches:
     - main
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
    uses: fastify/workflows/.github/workflows/plugins-ci-package-manager.yml@ef591e2186785d5ab36b9fe6a79c7ce2f1d94e57 # v7.0.0
